# This file automates building the Docker Image
name: Docker Image Build

# Trigger on new version release
on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]

# Build the Docker Image
jobs:
  # version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
  #       name: Get the version
  #       id: get_version
  #       run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
  #     -
  #       name: Print version
  #       run: echo ${{ steps.get_version.outputs.VERSION }}
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cur -d / -f 3)
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chargje/utc-time:latest, chargje/utc-time:${{ steps.get_version.outputs.VERSION }}