# This file automates building the Docker Image
name: Docker Image Build

# Trigger on new version release
on:
  push:
    branches:
      - main
    tags:
      - v[0-9].[0-9].[0-9]

# Build the Docker Image
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SUCCESS"
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: chargje/utc-time:latest